# Generated by Django 4.1.7 on 2023-03-05 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sora', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sora',
            name='noOfVerses',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='number Of Verses'),
        ),
    ]
