# Generated by Django 4.1.7 on 2023-03-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Audio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='type',
            field=models.CharField(choices=[('0', 'Murattal'), ('1', 'Mujawwad')], max_length=50, verbose_name='Audio Type'),
        ),
    ]
