# Generated by Django 4.1.7 on 2023-03-02 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Aya', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookMark',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Time')),
                ('aya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BookMarks', to='Aya.aya', verbose_name='Aya')),
            ],
            options={
                'verbose_name': 'BookMark',
                'verbose_name_plural': 'BookMarks',
            },
        ),
    ]
