# Generated by Django 4.1.7 on 2023-03-02 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Sora', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aya',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('ayaid', models.PositiveSmallIntegerField(verbose_name='Ayaid')),
                ('page', models.PositiveSmallIntegerField(verbose_name='Page')),
                ('quarter', models.SmallIntegerField(verbose_name='Quarter')),
                ('hezb', models.PositiveSmallIntegerField(verbose_name='Hezb')),
                ('joza', models.PositiveSmallIntegerField(verbose_name='Joza')),
                ('sajda', models.BooleanField(verbose_name='Sajda')),
                ('text', models.TextField(verbose_name='Text')),
                ('uthmanitext', models.TextField(verbose_name='Uthmani Text')),
                ('searchtext', models.TextField(verbose_name='Search Text')),
                ('quarterstart', models.BooleanField(verbose_name='Quarter Start')),
                ('soraid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ayat', to='Sora.sora', verbose_name='Soraid')),
            ],
            options={
                'verbose_name': 'Aya',
                'verbose_name_plural': 'Ayat',
                'unique_together': {('soraid', 'ayaid')},
            },
        ),
    ]
