# Generated by Django 4.1.7 on 2023-03-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tafseer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tafseer',
            name='type',
            field=models.CharField(choices=[('1', 'Type1'), ('2', 'Type2'), ('3', 'Type3'), ('4', 'Type4')], max_length=1, verbose_name='Type'),
        ),
    ]
